
INSERT INTO cs425.tblCourses (
    courseCode,
    courseName,
    status,
    credits,
    Description,
    majorID,
    meetingDays,
    startTime,
    endTime,
    meetingTimes,
    Requirements,
    classAttributes,
    Section,
    Room,
    instructor,
    startDate,
    endDate,
    classCapacity,
    enrollmentTotal,
    availableSeats,
    waitList,
    materials
) VALUES (
    'CS 135',
    'Computer Science I',
    'Open',
    3,
    'Introduction to modern problem solving and programming methods. Emphasis is placed on algorithm development. Introduction to procedural and data abstraction, emphasizing design, testing, and documentation.',
    1000,
    'TuTh',
    '11:00',
    '12:15',
    '11:00 AM - 12:15 AM',
    'Prerequisite(s): MATH 127 or MATH 128 or MATH 181 or MATH 182 or ACT Math score of 28 or SAT score of 650 or Accuplacer QAS 276 and AFF 285 or ALEKS PPL 76 or Business major and MATH 176.',
    'Lab fee for this course is $30',
    1001,
    'SEM 101',
    'Erin Keith',
    '2024-1-22',
    '2024-05-07',
    218,
    200,
    18,
    0,
    'Textbooks to be determined'),
    
('CS 202',
    'Computer Science II',
    'Open',
    3,
    'Emphasis on problem solving and program development techniques. Typical numerical and non-numerical problems are examined. Design, implementation, and abstraction principles of elementary data structures.',
    1000,
    'MoWe',
    '09:00',
    '10:30',
    '9:00 AM - 10:30 AM',
    'Prerequisite(s): CS 135 with a "C" or better.  Corequisite(s): ENGR 100 for CSE majors. Recommended Preparation: Basic program design, understanding, ability to use functions, declaration, single, multidimensional arrays, basic stream I/O',
    'Lab fee for this course is $35',
    1102,
    'WPEB 100',
    'Bashira Akter Anima',
    '2024-1-22',
    '2024-05-07',
    30,
    0,
    30,
    0,
    'Textbooks to be determined'
),

('CS 219',
    'Computer Organization',
    'Open',
    3,
    'Introduction to organization and integration of computer components. Topics include: computer abstractions and performance, arithmetic operations, instruction set architecture, assembly programming, datapath, pipelining, memory hierarchy, I/O, and parallel architectures.',
    1000,
    'MW',
    '16:00',
    '17:15',
    '4:00 PM - 5:15 PM',
    'Prerequisite(s): CPE 201 with a "C" or better; CS 202 with a "C" or better.',
    'Lab fee for this course is $25',
    1001,
    'SLH 2',
    'Bashira Akter Anima',
    '2024-1-22',
    '2024-05-07',
    100,
    60,
    40,
    0,
    'Textbooks to be determined'
),

('CS 252',
    'Computer Organization',
    'Closed',
    3,
    'Introduction to the basic computer and networking, forensic process, digital evidence collection, preserving the evidentiary chain, cybercrime statutes, and the legal aspects of search and seizure.',
    1000,
    'TuTh',
    '10:30',
    '11:45',
    '10:30 AM - 11:45 AM',
    null,
    null,
    1001,
    'LME 321',
    'Nancy Latourrette',
    '2024-1-22',
    '2024-05-07',
    32,
    32,
    0,
    0,
    'Textbooks to be determined'
),

('CS 302',
    'Computer Organization',
    'Open',
    3,
    'Data structures and algorithms fundamental to computer science; abstract data-type concepts; measures of program running time and time complexity; algorithm analysis and design techniques.',
    1000,
    'MoWe',
    '13:00',
    '14:15',
    '1:00 PM - 2:15 PM',
    'Prerequisite(s): CS 202 with a "C" or better.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'MS 215',
    'Erin Keith',
    '2024-1-22',
    '2024-05-07',
    114,
    102,
    12,
    0,
    'Textbooks to be determined'
),

('CS 326',
    'Programming Languages, Concepts and Implementation',
    'Open',
    3,
	'An overview of programming languages; features, structures, and implementation; examples taken from various programming paradigms. Introduction to formal specifications of languages.',
    1000,
    'MoWe',
    '09:00',
    '10:15',
    '9:00 AM - 10:15 AM',
    'Prerequisite(s): CS 302 with a "C" or better.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'DMSC 105',
    'Mircea Nicolescu',
    '2024-1-22',
    '2024-05-07',
    83,
    62,
    21,
    0,
    'Textbooks to be determined'
),

	
('CS 333',
    'Testing and DevOps',
    'Open',
    3,
    'Introduction to software testing methods and infrastructure as code.',
    1000,
    'MoWe',
    '16:30',
    '19:15',
    '4:30 PM - 7:15 PM',
    'Prerequisite(s): CS 302 with a "C" or better.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'WPEB 100',
    'Erin Keith',
    '2024-1-22',
    '2024-05-07',
    58,
    55,
    3,
    0,
    'Textbooks to be determined'
),

('CS 365',
    'Mathematics of Computer Science',
    'Open',
    3,
    'Computing related mathematical constructs and concepts. Topics covered include: propositional/predicate logic, proofs, sets functions algorithms, matrices, sequences, induction, recursion, combinatorics, probability, relations, graphs.',
    1000,
    'MoTuWeThFr',
    '10:00',
    '13:00',
    '10:00 AM - 1:00 PM',
    'Prerequisite(s): CS 202 with a "C" or better; MATH 182 with a "C" or better.',
    'This is a Direct Access course. Fees will vary.$85.00/credit differential undergraduate fee',
    1001,
    'WRB 2008',
    'Diana Moss',
    '2024-1-22',
    '2024-05-07',
    40,
    21,
    19,
    0,
    'Textbooks to be determined'
),

('CS 381',
    'Game Engine Architecture',
    'Open',
    3,
    'Introduction to the technical elements of modern videogame and the pipeline for assembling them, plus issues of interface design, quality assurance, and business practice.',
    1000,
    'MoWe',
    '14:30',
    '15:45',
    '2:30 PM - 3:45 PM',
    'Prerequisite(s): CS 202',
    '$85.00/credit differential undergraduate fee',
    1001,
    'WPEB 100',
    'Joshua Dahl',
    '2024-1-22',
    '2024-05-07',
    57,
    55,
    2,
    0,
    'Textbooks to be determined'
),

('CS 426',
    'Senior Projects in Computer Science',
    'Open',
    3,
    'Supervised group or team projects with emphasis on implementation of engineered design.',
    1000,
    'TuTh',
    '10:30',
    '11:45',
    '10:30 AM - 11:45 PM',
    'Prerequisite(s):  CSE major; Junior or Senior standing; CS 425 with a "C" or better.',
    'May satisfy Application (CO14) requirement. $85.00/credit differential undergraduate fee',
    1001,
    'SEM 101',
    'Dave Feil-Seifer',
    '2024-1-22',
    '2024-05-07',
    100,
    100,
    0,
    0,
    'Textbooks to be determined'
),

('CS 453',
    'Mobile Computing Security and Privacy',
    'Open',
    3,
    'Emerging topics on security and privacy in mobile computing, including misbehavior detection in wireless networks, wireless routing privacy, malicious access point detection, cognitive authentication, privacy protection.',
    1000,
    'TuTh',
    '15:00',
    '16:15',
    '3:00 PM - 4:15 PM',
    'Prerequisite(s): CPE 400 or CPE 401.',
    null,
    1001,
    'WPEB 100',
    'William Doherty',
    '2024-1-22',
    '2024-05-07',
    43,
    41,
    2,
    0,
    'Textbooks to be determined'
),

('CS 446',
    'Principles of Operating Systems',
    'Open',
    3,
    'Concurrent processes, interprocess communication, processor management, virtual and real memory management, deadlock, file systems, disk management, performance issues, case studies. Practical experience with UNIX.',
    1000,
    'TuTh',
    '15:00',
    '16:15',
    '3:00 PM - 4:15 PM',
    'Prerequisite(s): CS 105 or ENGR 100; CS 219 with a "C" or better; CS 302 with a "C" or better. Corequisite(s): ENGR 301 (for CSE majors only).',
    'May satisfy Ethics (CO12) requirement. $85.00/credit differential undergraduate fee',
    1001,
    'JTB 100',
    'Sara Davis',
    '2024-1-22',
    '2024-05-07',
    140,
    91,
    49,
    0,
    'Textbooks to be determined'
),

('CS 431',
    'Introduction to Big Data',
    'Open',
    3,
    'This course offers an introduction to big data techniques and applications. It covers basic topics like Big Data Overview, Big Data Management, Big Data Modeling, Big Data Analytics, Big Data Tools, and Big Data Applications.',
    1000,
    'TuTh',
    '16:30',
    '17:45',
    '4:30 PM - 5:45 PM',
    'Prerequisite(s): CS 302 with a "C" or better; STAT 352 or STAT 461 with a "C" or better',
    'May satisfy Ethics (CO12) requirement. $85.00/credit differential undergraduate fee',
    1001,
    'DMSC 102',
    'Lei Yang',
    '2024-1-22',
    '2024-05-07',
    62,
    51,
    11,
    0,
    'Textbooks to be determined'
),

('CS 456',
    'Automata and Formal Languages',
    'Open',
    3,
    'Fundamental concepts of computation. Relationship between grammars, languages and machines, emphasizing regular and context free languages, finite state acceptors and Turing machines. Complexity and computability.',
    1000,
    'TuTh',
    '15:00',
    '16:15',
    '3:00 PM - 4:15 PM',
    'Prerequisite(s): CS 302 with a "C" or better; CS 365 with a "C" or better; MATH 283.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'SLH 2',
    'Nancy Latourrette',
    '2024-1-22',
    '2024-05-07',
    105,
    97,
    8,
    0,
    'Textbooks to be determined'
),

('CS 457',
    'Database Management Systems',
    'Open',
    3,
    'An overview of existing systems; physical data organization; relational, network and hierarchical models; data manipulation languages, data definition languages; database protection; database application using INGRES.',
    1000,
    'MoWe',
    '13:30',
    '14:45',
    '1:30 PM - 2:45 PM',
    'Prerequisite(s): CS 302 with a "C" or better; CS 365 or EE 291.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'DMSC 110',
    'Monica Nicolescu',
    '2024-1-22',
    '2024-05-07',
    83,
    81,
    2,
    0,
    'Textbooks to be determined'
),

('CS 477',
    'Analysis of Algorithms',
    'Open',
    3,
    'Analysis and design of algorithms on sequences, sets, graphs and trees. Geometric, algebraic and numeric algorithms, FFTs, reductions. Parallel algorithms.',
    1000,
    'TuTh',
    '14:30',
    '15:45',
    '2:30 PM - 3:45 PM',
    'Prerequisite(s): CS 302.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'DMSC 110',
    'Monica Nicolescu',
    '2024-1-22',
    '2024-05-07',
    140,
    113,
    27,
    0,
    'Textbooks to be determined'
),

('CS 479',
    'Pattern Recognition',
    'Open',
    3,
    'Pattern recognition systems, statistical methods, discrimination functions, clustering analysis, unsupervised learning, feature extraction and feature processing.',
    1000,
    'MoWe',
    '13:00',
    '14:15',
    '1:00 PM - 2:15 PM',
    'Prerequisite(s): CS 202 with a "C" or better; STAT 352 or STAT 461.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'WPEB 200',
    'George Bebis',
    '2024-1-22',
    '2024-05-07',
    37,
    30,
    7,
    0,
    'Textbooks to be determined'
    ),


('CS 484',
    'Virtual Reality',
    'Open',
    3,
    'Students will learn about sensor, display, and computing technology as well as human perceptual and motor processes that underlie virtual reality technology. (CS 484 and PSY 484 are cross-listed; credits may be earned in one of the two.)',
    1000,
    'TuTh',
    '13:30',
    '14:45',
    '1:30 PM - 2:45 PM',
    'Prerequisite(s): Junior or senior standing.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'AB 101',
    'Eelke Folmer',
    '2024-1-22',
    '2024-05-07',
    80,
    76,
    4,
    0,
    'Textbooks to be determined'
    ),
    
('CS 485',
    'Computer Vision',
    'Open',
    3,
    'Principles, design and implementation of vision systems. Camera models and image formation, feature detection, segmentation. Camera calibration, 3-D reconstruction, stereo vision. Introduction to advanced topics.',
    1000,
    'TuTh',
    '09:00',
    '10:15',
    '9:00 AM - 10:15 AM',
    'Prerequisite(s): CS 302 with a "C" or better.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'WPEB 200',
    'Emily Hand',
    '2024-1-22',
    '2024-05-07',
    36,
    25,
    1,
    0,
    'Textbooks to be determined'
    ),
    
    
('CS 485',
    'Fundamentals of Deep Learning',
    'Open',
    3,
    'Principles, design and implementation of vision systems. Camera models and image formation, feature detection, segmentation. Camera calibration, 3-D reconstruction, stereo vision. Introduction to advanced topics.',
    1000,
    'MoWe',
    '16:00',
    '17:15',
    '4:00 PM - 5:15 PM',
    'Prerequisite(s): CS 302 with "C" or better; MATH 330. Recommended Preparation: Machine Learning, solid mathematical background and good programming skills.',
    '$85.00/credit differential undergraduate fee',
    1001,
    'DMSC 102',
    'Alireza Tavakkoli',
    '2024-1-22',
    '2024-05-07',
    61,
    56,
    5,
    0,
    'Textbooks to be determined'
    );